apiVersion: v1
kind: Service
metadata:
  name: bel-fastapi-loadbalancer
  labels:
    app: bel-fastapi
spec:
  selector:
    app: bel-fastapi
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer
